INSERT INTO categories (id, name, slug, icon, active) VALUES
('cat_technology', 'Technology', 'technology', 'laptop', TRUE),
('cat_agriculture', 'Agriculture', 'agriculture', 'leaf', TRUE),
('cat_manufacturing', 'Manufacturing', 'manufacturing', 'factory', TRUE),
('cat_energy', 'Energy', 'energy', 'bolt', TRUE),
('cat_healthcare', 'Healthcare', 'healthcare', 'heart', TRUE),
('cat_education', 'Education', 'education', 'book', TRUE),
('cat_finance', 'Finance', 'finance', 'wallet', TRUE),
('cat_real_estate', 'Real Estate', 'real-estate', 'home', TRUE),
('cat_construction', 'Construction', 'construction', 'hardhat', TRUE),
('cat_transport_logistics', 'Transport & Logistics', 'transport-logistics', 'truck', TRUE),
('cat_tourism_hospitality', 'Tourism & Hospitality', 'tourism-hospitality', 'hotel', TRUE),
('cat_food_beverage', 'Food & Beverage', 'food-beverage', 'utensils', TRUE),
('cat_retail_ecommerce', 'Retail & E-commerce', 'retail-ecommerce', 'shopping-cart', TRUE),
('cat_fashion_beauty', 'Fashion & Beauty', 'fashion-beauty', 'sparkle', TRUE),
('cat_automotive', 'Automotive', 'automotive', 'car', TRUE),
('cat_mining', 'Mining', 'mining', 'pickaxe', TRUE),
('cat_oil_gas', 'Oil & Gas', 'oil-gas', 'droplet', TRUE),
('cat_telecommunications', 'Telecommunications', 'telecommunications', 'radio', TRUE),
('cat_media_entertainment', 'Media & Entertainment', 'media-entertainment', 'film', TRUE),
('cat_sports_fitness', 'Sports & Fitness', 'sports-fitness', 'activity', TRUE),
('cat_government_public_sector', 'Government & Public Sector', 'government-public-sector', 'landmark', TRUE),
('cat_ngos_development', 'NGOs & Development', 'ngos-development', 'hand-heart', TRUE),
('cat_environment_climate', 'Environment & Climate', 'environment-climate', 'globe', TRUE),
('cat_water_sanitation', 'Water & Sanitation', 'water-sanitation', 'droplet', TRUE),
('cat_security_safety', 'Security & Safety', 'security-safety', 'shield', TRUE),
('cat_legal_professional_services', 'Legal & Professional Services', 'legal-professional-services', 'scale', TRUE),
('cat_business_services', 'Business Services', 'business-services', 'briefcase', TRUE),
('cat_human_resources', 'Human Resources', 'human-resources', 'users', TRUE),
('cat_marketing_advertising', 'Marketing & Advertising', 'marketing-advertising', 'megaphone', TRUE),
('cat_art_culture', 'Art & Culture', 'art-culture', 'palette', TRUE),
('cat_furniture_interiors', 'Furniture & Interiors', 'furniture-interiors', 'sofa', TRUE),
('cat_home_living', 'Home & Living', 'home-living', 'home', TRUE),
('cat_electronics', 'Electronics', 'electronics', 'monitor', TRUE),
('cat_software_saas', 'Software & SaaS', 'software-saas', 'code', TRUE),
('cat_hardware_devices', 'Hardware & Devices', 'hardware-devices', 'cpu', TRUE),
('cat_ai_data', 'AI & Data', 'ai-data', 'bot', TRUE),
('cat_cybersecurity', 'Cybersecurity', 'cybersecurity', 'shield', TRUE),
('cat_robotics_automation', 'Robotics & Automation', 'robotics-automation', 'bot', TRUE),
('cat_packaging_printing', 'Packaging & Printing', 'packaging-printing', 'package', TRUE),
('cat_textiles', 'Textiles', 'textiles', 'scissors', TRUE),
('cat_pharmaceuticals', 'Pharmaceuticals', 'pharmaceuticals', 'pill', TRUE),
('cat_medical_devices', 'Medical Devices', 'medical-devices', 'stethoscope', TRUE),
('cat_banking_insurance', 'Banking & Insurance', 'banking-insurance', 'banknote', TRUE),
('cat_renewable_energy', 'Renewable Energy', 'renewable-energy', 'sun', TRUE),
('cat_agritech', 'Agritech', 'agritech', 'leaf', TRUE),
('cat_fintech', 'Fintech', 'fintech', 'wallet', TRUE),
('cat_proptech', 'Proptech', 'proptech', 'home', TRUE),
('cat_edtech', 'Edtech', 'edtech', 'book', TRUE),
('cat_healthtech', 'Healthtech', 'healthtech', 'heart', TRUE),
('cat_creative_economy', 'Creative Economy', 'creative-economy', 'palette', TRUE)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    icon = EXCLUDED.icon,
    active = EXCLUDED.active;
