ALTER TABLE products
  ADD COLUMN IF NOT EXISTS image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS demo_video_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS presentation_url TEXT NOT NULL DEFAULT '';
