ALTER TABLE expo_exhibitors
  ADD COLUMN IF NOT EXISTS estimated_spend_minor BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS roi_currency_code TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS roi_spend_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS roi_notes TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS roi_updated_at TIMESTAMPTZ;

