ALTER TABLE organizer_profiles
ADD COLUMN IF NOT EXISTS payout_method TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_account_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_bank_name TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_account_number TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_bank_branch TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_swift_code TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_mobile_provider TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_mobile_number TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS payout_notes TEXT NOT NULL DEFAULT '';

